# Generated by Django 6.0.4 on 2026-04-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_set', to='core.status')),
            ],
        ),
    ]
